### ISSUE TITLE
"Used by" section

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/cachethq.io#20]
Let's add a "Used by" section on the homepage with the logo of companies that are using Cachet. This builds trust too!

**Comment by jbrooksuk** [comment]
I like how [Readme.io](https://readme.io/) show their "Used by" and when you hover, the logo goes into full colour. Let's do that.

**Comment by joecohens** [comment]
:+1:

**Comment by SalGnt** [comment]
+1

**Comment by jbrooksuk** [comment]
Ok, so I know how we can do this:

- Get everyone who wants to be on the homepage to provide us with a high resolution PNG of their logo.
- We'll then add to Sketch/Fireworks and apply a colour filter of light grey (decided by @joecohens)
- Create a file of the grey and coloured versions.
- ReadMe.io do the same thing here (https://readme.io/img/homepage/logos.png)

**Comment by jbrooksuk** [comment]
Working on this under the `new` branch.
