### ISSUE TITLE
Copy Newsletter to top of site

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/cachethq.io#50]
The Newsletter could generate a lot more signups by moving it to the top/centre where it's more likely to be visible.

**Comment by GrahamCampbell** [comment]
How much is this newsletter costing btw?

**Comment by jbrooksuk** [comment]
It's free for now until we get thousands of subscribers basically.

**Comment by GrahamCampbell** [comment]
k

**Comment by GrahamCampbell** [comment]
How many currently? ~10?

**Comment by jbrooksuk** [comment]
If that.

**Comment by GrahamCampbell** [comment]
lol

**Comment by jbrooksuk** [comment]
4 subscribers. Lol. This is why we need to move it up.

**Comment by joecohens** [comment]
Now 5 LOL I'll move it.

**Comment by GrahamCampbell** [comment]
The funny thing is, one of them is me...

**Comment by jbrooksuk** [comment]
One is me too.

**Comment by joecohens** [comment]
This should be included in https://github.com/cachethq/cachethq.io/issues/55

**Comment by jbrooksuk** [comment]
We could probably close this and add it to the new issue actually.
