### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/cachethq.io#55]
Ok, if you take a look at [competitor](https://www.statuspage.io/) [websites](https://status.io/) they fully explain what the product is, who it will benefit (hobbies, teams, companies) and who currently uses it.

We'll also need to include (in no particular folder):

- Easier newsletter signup
- Screenshots
- Company/app logos
- What people are saying
- Demo video
- Key features

I think the current homepage is ok, but it could be a lot cleaner and more organised.

Thoughts, feedback?

**Comment by joecohens** [comment]
:+1:

**Comment by joecohens** [comment]
Agree with all of the above, we need to show and describe the features.

**Comment by jbrooksuk** [comment]
http://codyhouse.co/demo/animated-headlines/index.html

Check out the **Type** effect. We should use that to explain what Cachet can do?
