### ISSUE TITLE
"Donator" Is Not A Word!

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/cachethq.io#60]
"Donor" is a word however. :)

**Comment by jbrooksuk** [comment]
https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=define%3A%20donator

But "donor" is better.

**Comment by GrahamCampbell** [comment]
I don't think it's actually a word still. Google is just so clever that it think it's a word because so many people misuse it. For example, "performant" isn't a word, but I'll still use it. :)

**Comment by jbrooksuk** [comment]
True :)
