### ISSUE TITLE
Making the list of functions more readable.

### ISSUE THREAD

**Issue by rodymol123** [cachethq/cachethq.io#70]
After looking at the website for a good hour i've come to the conclusion that the font is actually too slim to read properly (with ease). I suggest using the normal font-weight (500) and reducing the bottom margin of .mb from 50px(!) tot 30px.

Example: 
![Example](http://i.imgur.com/TqEB9oq.png)

Versus:
![versus](http://i.imgur.com/Tiu5lHJ.png)

**Comment by jbrooksuk** [comment]
It's worth trying! If it's easier to read then we need to sort it.
